# Generated by Django 3.2.5 on 2021-07-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210730_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, through='users.UserSkill', to='users.Skill'),
        ),
    ]
