# Generated by Django 3.2.5 on 2021-08-01 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_user_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('S', 'Startup'), ('N', 'Nonprofit'), ('R', 'Research')], default='S', max_length=1)),
                ('stage', models.CharField(choices=[('I', 'Idea stage'), ('P', 'Prototype'), ('C', 'Completed')], default='I', max_length=1)),
                ('looking_for', models.CharField(blank=True, default='', max_length=512)),
                ('skills_needed', models.ManyToManyField(to='users.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(through='projects.UserProject', to=settings.AUTH_USER_MODEL),
        ),
    ]
